apiVersion: v1
kind: Service
metadata:
  name: verifier-service
  namespace: dgca-test
  labels:
    app: verifier-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: verifier-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verifier-service
  namespace: dgca-test
  labels:
    app: verifier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verifier-service
  template:
    metadata:
      labels:
        app: verifier-service
    spec:
      volumes:
        - name: destination
          secret:
            secretName: destination-service-binding-verifier
        - name: xsuaa
          secret:
            secretName: uaa-service-binding-verifier
      imagePullSecrets:
        - name: regcred
      containers:
        - name: verifier-service
          image: docker.pkg.github.com/courobin/dgca-verifier-service/dgca-verifier-service:1.0.5-ea7576e
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dgca-verifier-service
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 443
          volumeMounts:
            - name: destination
              mountPath: "/etc/secrets/sapcp/destination/destination-service-instance-verifier"
              readOnly: true
            - name: xsuaa
              mountPath: "/etc/secrets/sapcp/xsuaa/uaa-service-instance-verifier"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /signercertificateStatus
              port: 8080
              
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: uaa-service-instance-verifier
  namespace: dgca-test
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: xsuaa-kyma-verifier
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*/**
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: uaa-service-binding-verifier
  namespace: dgca-test
spec:
  secretName: uaa-service-binding-verifier
  serviceInstanceName: uaa-service-instance-verifier

---
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: destination-service-instance-verifier
  namespace: dgca-test
spec:
  externalName: destination
  serviceOfferingName: destination
  servicePlanName: lite
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: destination-service-binding-verifier
  namespace: dgca-test
spec:
  secretName: destination-service-binding-verifier
  serviceInstanceName: destination-service-instance-verifier              
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: uaa-service-binding-verifier
  namespace: dgca-test
spec:
  instanceRef:
    name: uaa-service-instance-verifier
