apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-verifier
  namespace: dgca-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-verifier
  template:
    metadata:
      labels:
        app: db-verifier
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: db-verifier
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: dgca-verifier
          volumeMounts:
            - name: verifierdb
              mountPath: /var/opt/verifier/postgresql
      volumes:
        - name: verifierdb
          persistentVolumeClaim:
            claimName: postgres-verifier
---
apiVersion: v1
kind: Service
metadata:
  name: db-verifier
  namespace: dgca-test
  labels:
    app: db-verifier
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: db-verifier
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-verifier
  namespace: dgca-test
  labels:
    app: db-verifier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
